### ISSUE TITLE
status of server code is unclear

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-xenstore-server#4]
In trying to use this Xenstore daemon for data sharing between VMs I discovered that this doesn't seem to be possible, as almost all the relevant-seeming code in `server/` is commented out and, when uncommented, doesn't compile.  It's difficult for me to evaluate how much work would be required to get this code into a runnable state -- can someone more familiar with the project provide some advice?

**Comment by djs55** [comment]
Iirc last thing I was thinking of was xenstore watches. If the semantics of
irmin watches are similar enough then we could just use them. Otherwise
we'll need something custom, computing the necessary watch events and
storing in an irmin-based queue (more work, more of a pain, less efficient)

**Comment by samoht** [comment]
The semantics of watches should be quite similar.

**Comment by yomimono** [comment]
I'll attempt to be clearer: have a look at https://github.com/mirage/ocaml-xenstore-server/blob/master/server/connection.ml .  It looks like this (and a lot of other code in `server/`) needs to be uncommented to have a `xenstored` that actually does anything when Xen guests connect to it, but uncommenting this code (and the code it calls, etc etc) results in a build failure:

```
$ make
W: Cannot find source file matching module 'xenstored' in library xenstored
W: Cannot find source file matching module 'xenstore' in library xenstore
Finished, 0 targets (0 cached) in 00:00:00.
Configuration "true: quiet, debug, tests", line 1, characters 20-25:
Warning: the tag "tests" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
+ /home/dothraki/.opam/separate-arp-tcpip/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I core -package cstruct -syntax camlp4o -package cstruct.syntax -package git -package irmin -package irmin.unix -package lwt -syntax camlp4o -package lwt.syntax -package sexplib -syntax camlp4o -package sexplib.syntax -package uri -syntax camlp4o -I server -I core -o server/transaction.cmo server/transaction.ml
File "server/transaction.ml", line 44, characters 2-6:
Error: Unbound value view
Command exited with code 2.
Compilation unsuccessful after building 53 targets (51 cached) in 00:00:00.
E: Failure("Command ''/home/dothraki/.opam/separate-arp-tcpip/bin/ocamlbuild' core/xenstore.cma core/xenstore.cmxa core/xenstore.a core/xenstore.cmxs server/xenstored.cma server/xenstored.cmxa server/xenstored.a server/xenstored.cmxs unix/xenstore_unix.cma unix/xenstore_unix.cmxa unix/xenstore_unix.a unix/xenstore_unix.cmxs core_test/core_test.native userspace/main.native cli/cli.native bench/bench.native -tag debug -tag tests -j 4' terminated with error code 10")
make: *** [build] Error 1
```

Since so much of the code is commented out, I assume that only some subset of the functionality described in the README is actually expected to be present.  What's that subset, and what's the estimate of how much work would be required to have the functionality described in the README?

**Comment by yomimono** [comment]
The tree which yields the above build error is [here](https://github.com/yomimono/ocaml-xenstore-server/tree/uncomment_stuff).

**Comment by djs55** [comment]
I'll try to take a look later today to figure out what needs doing to get it back to a decent state. The recent history is something like:

I added basic support for Irmin (an old version of) but still kept using the parallel code to compute watches. Meanwhile I then spent some time debugging a horrible problem in the old xenstored where it couldn't be restarted without rebooting the host (and all the VMs). This experience made me think it would be a good idea to persist all state updates to make it resilient to sudden crashes and restart. To make it restartable I would have to keep track of where we are in the rings, so that read() and write() could be made idempotent -- this required shared-memory-ring changes (now done). I then needed to persist partial writes somewhere -- initially I made them temporary commits to Irmin but this was a bit slow. I backtracked and decided to keep additional persistent buffers (e.g. via /dev/shm) for this temporary data, which is nice and fast. Finally, to make the benchmark work quickly I ended up quickly commenting out the inter domain code temporarily.

Sorry for all the confusion!

**Comment by djs55** [comment]
Latest update -- I've started hooking up the xenstore watches with the Irmin watch API. So far it seems like a good fit. Once that's done I *hope* it will actually work on a live system again.

**Comment by yomimono** [comment]
That's great! Thanks for the update.

**Comment by yomimono** [comment]
@djs55 I haven't been looking at this in quite some time - is there working server code here?  It looks like lots of stuff is still commented out.

**Comment by djs55** [comment]
Unfortunately I've not had time to work on it (since Aug 2015!). I think it still requires quite a lot of effort to get into a working state, and then to catch up with relevant bug fixes in the default (non-irmin) xenstored.

I also wonder whether it's worth it. The approach here is to write the key=value pairs directly into the irmin store as strings. It's a bit ad-hoc, maybe it would be better to try to retrospectively figure out the structure (devices, domains, states etc) and then store high-level information in the store and fake the low-level protocol messages in per-domain adapters. A bit like a connection-tracking firewall? Just a thought though!

**Comment by yomimono** [comment]
I think I'll close this, as I'm not invested in what happens and I doubt I have anything useful to contribute to how this problem is solved by the current maintainers.  Thanks for the update @djs55 :)
